### ISSUE TITLE
[EPIC] Data flow

### ISSUE THREAD

**Issue by andy-verida** [verida/vault-web#1]
```[tasklist]
### Tasks
- [x] Render folders
- [x] Fetch DB
- [x] Render credential
- [ ] Render normal data record
- [ ] Validate credential types
- [ ] Fix the server API to fetch public profiles(optimize cache and SEO)
- [ ] Base layouts responsiveness
- [ ] TBA
```
