### ISSUE TITLE
[Epic] Connections page design

### ISSUE THREAD

**Issue by tahpot** [verida/vault-web#2]
```[tasklist]
### Tasks
- [x] Implement `Connections` page. See [Figma design](https://www.figma.com/file/Xg9FprLNWFknCz89CVu9Kf/Verida-Vault-Web-App?type=design&node-id=267-19678&mode=design&t=p6yaxCIT0Nt418JI-0)
- [x] Support hardcoded list of Connections in the application config
- [x] Support Connect modal. See [Figma design](https://www.figma.com/file/Xg9FprLNWFknCz89CVu9Kf/Verida-Vault-Web-App?type=design&node-id=348-21515&mode=design&t=p6yaxCIT0Nt418JI-0)
- [x] Support search connections
```

Note: Linking to our data connections API will be a separate task
