### ISSUE TITLE
Integrate the Data Connector API

### ISSUE THREAD

**Issue by tahpot** [verida/vault-web#4]
```[tasklist]
### Tasks
- [x] Render available connections using `DataConnectorsManager.getConnections()`
- [x] Clicking `Connect` on a connection redirect the user to connect using `DataConnectorsManager.getConnection()` and `connection.getConnectUrl()`
- [x] Configure `Connect` to embed a `redirect` URL so the user is redirect to the connect page in `vault-web`. See `redirect` functionality in [connect()](https://github.com/verida/data-connector-server/blob/a3ca479787dbda2fffdf567bbf8e41856c85e0c7/src/controller.ts#L53) and [callback](https://github.com/verida/data-connector-server/blob/a3ca479787dbda2fffdf567bbf8e41856c85e0c7/src/controller.ts#L81)
- [x] Listen to `connectionUpdated`, `connectionDisconnectError` from `DataConnectorsManager` and log to console
- [x] When the user has successfully connected call `DataConnectorsManager.triggerSync()`
```

If you successfully sync to `Discord` (I think) you will see your discord groups in `data/social/following`.

## DataConnectorsManager (DCM)

There is a [DataConnectorsManager](https://github.com/verida/vault-web/blob/3939d05c19f71cefc9e9f2b693b530ef1fe69459/lib/DataConnectorManager.ts) library. This has been pulled from our mobile app with a few slight modifications, but the code has never been run in this `vault-web` app, so it may have some issues

It supports fetching a connection object (ie: `DataConnectorsManager.getConnection('disord')`).

There is some example code showing how this works in [connections/page.tsx](https://github.com/verida/vault-web/blob/3939d05c19f71cefc9e9f2b693b530ef1fe69459/app/(root)/(routes)/connections/page.tsx#L44)

This is roughly how the DataConnectorsManager works with the Data Connector Server:

**Connecting:**

1. Obtain a connection URL
2. Redirect the user to the connection URL on the Data Connector Server
3. Data Connector Server redirects the user to authenticate with the API (ie: Discord)
4. User successfully authenticates and is redirected to the `callback()` endpoint on Data Connector Server
5. Data Connector Server redirects the user back to the `vault-web` application, providing auth tokens
6. Data Connector Manager opens an encrypted database and saves the user's auth tokens

**Syncing:**

1. Call `DataConnectorsManager.triggerSync()`
2. This iterates through all the user's active connections and initiates a sync
3. An encrypted database and encryption key is generated for the sync
4. `DataConnectorsManager` makes an API request to the Data Connector Server to sync a given connection. It provides the auth token, encryption key and database details
5. The Data Connector Server process the request, connects to the remote API with the auth token and creates database entries in the encrypted database
6. Once complete the Data Connector Server updates a `status` database specifying the status of the sync (`success` / `fail`)
7. The `DataConnectorsManager` monitors the `status` database and once the status is updated, it handles any errors, or if the sync was successful, it migrates the data from the sync database into the user's appropriate `Verida: Vault` database. This ensures the `Data Connector Server` never gets access to all the user's data, only the data that is sync'd from the remote API

## Environment setup

You will need to:

1. Clone the [Data Connector Server](https://github.com/verida/data-connector-server) (DCS) locally.
8. Configure DCS (`/srcs/serverconfig.json`) so it has a single `providers` entry for `discord`. You will need to create your own Discord API key and configure it to accept requests from your local IP address. The callback URL is `http://<your-ip>/callback/discord`
9. Run the DCS (`yarn run dev`)
10. In this `vault-web` repo, update `/lib/DataConnectorManager.ts` / `DATA_CONNECTOR_URL` to point to your running DCS.
